### PR TITLE
Add support for unique_id

### PR DESCRIPTION
**Pull request by codyc1515**
Fixes #

Description of change:

## Formatting, testing, and code coverage
Please note your pull request won't be accepted if you haven't properly formatted your source code, and ensured the unit tests are appropriate.  Please note if you are not running on Windows, you can either run the scripts via a bash installation (like git-bash).

- [] formatstyle.sh reports no errors
- [] All unit tests pass (test.sh)
- [] Code coverage has not decreased (test.sh)

### CODE REVIEW

**Comment by metbril** [comment]
Fixes #89 ?

**Comment by codyc1515** [comment]
Sorry, yes

**Comment by franc6** [comment]
Please see [https://developers.home-assistant.io/docs/config_entries_config_flow_handler](https://developers.home-assistant.io/docs/config_entries_config_flow_handler), particularly the following text:

> ### Unacceptable sources for a unique ID
> 
> * IP Address
> * Device Name
> * Hostname if it can be changed by the user
> * URL

The right way to support a unique ID is to make it use ConfigFlow, which so far hasn't been possible, because the calendar component doesn't support ConfigFlow, and this "integration" is just a platform for the calendar component.

You can configure Google calendars in the UI because that's part of the Google component -- you can't configure a stand-alone Google calendar through the UI, but you can through YAML configuration.  Worse, the new local calendars that Home Assistant has added are also their own stand-alone component.

After reviewing several other components in the source tree, I think I'm going to break compatibility, in two or three phases.  

Phase 1: Version 4.0:
Shift this project to providing its own component.  You'll have to modify your YAML config a little (but not a lot) for this change.  Basically, you'll take a config like this:

```yaml
calendar:
- platform: ics_calendar
  calendars:
      - name: "Name of calendar"
        url: "https://url.to/calendar.ics"
```

to this:

```yaml
ics_calendar:
- calendars:
      - name: "Name of calendar"
        url: "https://url.to/calendar.ics"
```
Phase 2: Version X.x:
This phase will add support for UI configuration via ConfigFlow.  This will convert existing YAML configuration (and remove it?).  Phase 2 will not be released for at least 3 months after the release of 4.0, to ensure that users have a chance to make the change for phase 1.  Users upgrading to this release from 3.x or earlier will have big problems, while users upgrading from 4.0 (or later) shouldn't notice much difference, if any.

Phase 3: Version X.x:
This final phase will eliminate reading configuration from YAML, meaning configuration will only be through the UI.  This third phase might never happen, depending on feedback received.  Or, depending on other changes in HA (which may have already happened, and I just haven't noticed), might happen with Phase 2, or happen even without any coding changes to this project.

**Comment by codyc1515** [comment]
That's true but this isn't HA Core so we could look to fix it later.

**Pull request closed without merging**
